export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const GET_AUTH_USER = "GET_AUTH_USER"
export const GET_AUTH_USER_SUCCESS = "GET_AUTH_USER_SUCCESS"
export const GET_AUTH_USER_FAILED = "GET_AUTH_USER_FAILED"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILED = "LOGOUT_FAILED"

