export const CREATE_ORDER = "CREATE_ORDER"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED"

export const MY_ORDERS = "MY_ORDERS"
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS"
export const MY_ORDERS_FAILED = "MY_ORDERS_FAILED"

export const ORDER_DETAILS = "ORDER_DETAILS"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAILED = "ORDER_DETAILS_FAILED"

export const ALL_ORDERS = "ALL_ORDERS"
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS"
export const ALL_ORDERS_FAILED = "ALL_ORDERS_FAILED"
