export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_ALL_PRODUCTS_FAILED = "GET_ALL_PRODUCTS_FAILED"

export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID"
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS"
export const GET_PRODUCT_BY_ID_FAILED = "GET_PRODUCT_BY_ID_FAILED"

export const REVIEW = "REVIEW"
export const REVIEW_SUCCESS = "REVIEW_SUCCESS"
export const REVIEW_FAILED = "REVIEW_FAILED"

export const GET_REVIEWS = "GET_REVIEWS"
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS"
export const GET_REVIEWS_FAILED = "GET_REVIEWS_FAILED"

export const ADMIN_GET_ALL_PRODUCTS = "ADMIN_GET_ALL_PRODUCTS"
export const ADMIN_GET_ALL_PRODUCTS_SUCCESS = "ADMIN_GET_ALL_PRODUCTS_SUCCESS"
export const ADMIN_GET_ALL_PRODUCTS_FAILED = "ADMIN_GET_ALL_PRODUCTS_FAILED"

export const ADMIN_CREATE_PRODUCTS = "ADMIN_CREATE_PRODUCTS"
export const ADMIN_CREATE_PRODUCTS_SUCCESS = "ADMIN_CREATE_PRODUCTS_SUCCESS"
export const ADMIN_CREATE_PRODUCTS_FAILED = "ADMIN_CREATE_PRODUCTS_FAILED"

export const ADMIN_DELETE_PRODUCTS = "ADMIN_DELETE_PRODUCTS"
export const ADMIN_DELETE_PRODUCTS_SUCCESS = "ADMIN_DELETE_PRODUCTS_SUCCESS"
export const ADMIN_DELETE_PRODUCTS_FAILED = "ADMIN_DELETE_PRODUCTS_FAILED"

export const ADMIN_UPDATE_PRODUCTS = "ADMIN_UPDATE_PRODUCTS"
export const ADMIN_UPDATE_PRODUCTS_SUCCESS = "ADMIN_UPDATE_PRODUCTS_SUCCESS"
export const ADMIN_UPDATE_PRODUCTS_FAILED = "ADMIN_UPDATE_PRODUCTS_FAILED"